CREATE TABLE Customers (
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    Phone VARCHAR(10) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    BillingAddress VARCHAR(255) NOT NULL,
    DateCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
    Author INT NOT NULL,
    FOREIGN KEY (Author) REFERENCES Employees(ROWID)
)