CREATE TABLE Products (
    SKU VARCHAR(255) NOT NULL,
    Description VARCHAR(255) NOT NULL,
    Price FLOAT NOT NULL,
    DateCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
    Author INT NOT NULL,
    FOREIGN KEY (Author) REFERENCES Employees(ROWID)
)