CREATE TABLE Products (
    SKU VARCHAR(255) NOT NULL,
    Description VARCHAR(255) NOT NULL,
    Price FLOAT NOT NULL,
    DateCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
    Author INT FOREIGN KEY REFERENCES Employees(ROWID)
)