CREATE TABLE Transactions (
    Customer INT FOREIGN KEY REFERENCES Customers(ROWID),
    POS VARCHAR(255) NOT NULL,
    Station VARCHAR(255) NOT NULL,
    DateCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
    Author INT FOREIGN KEY REFERENCES Employees(ROWID)
)