CREATE TABLE Transactions (
    Customer INT NOT NULL,
    POS VARCHAR(255) NOT NULL,
    Station VARCHAR(255) NOT NULL,
    DateCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
    Author INT NOT NULL,
    FOREIGN KEY (Customer) REFERENCES Customers(ROWID),
    FOREIGN KEY (Author) REFERENCES Employees(ROWID)
)