CREATE TABLE TransactionLineItems (
    SKU VARCHAR(255) FOREIGN KEY REFERENCES Products(SKU),
    Qty FLOAT NOT NULL,
    Price FLOAT NOT NULL,
    DateCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
    Author FOREIGN KEY REFERENCES Employees(ROWID),
    TransactionID FOREIGN KEY REFERENCES Transactions(ROWID)
)