CREATE TABLE TransactionLineItems (
    SKU VARCHAR(255) NOT NULL,
    Qty FLOAT NOT NULL,
    Price FLOAT NOT NULL,
    DateCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
    Author INT NOT NULL,
    TransactionID INT NOT NULL,
    FOREIGN KEY (SKU) REFERENCES Products(SKU),
    FOREIGN KEY (Author) REFERENCES Employees(ROWID),
    FOREIGN KEY(TransactionID) REFERENCES Transactions(ROWID)
)