CREATE TABLE Employees (
    FirstName VARCHAR(255) NOT NULL ,
    MiddleName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    DOB DATE NOT NULL,
    Sex VARCHAR(1) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Phone VARCHAR(10) NOT NULL,
    PayRate FLOAT NOT NULL,
    Role INT FOREIGN KEY REFERENCES Roles(ROWID),
    DateCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
    Author INT FOREIGN KEY REFERENCES Employees(ROWID)
)